baseURL = 'https://blog.fantasky.dpdns.org/'
languageCode = 'zh_cn'
title = 'Fantasky`s Blog'
theme = 'hugo-theme-monochrome'

[params]
    toc_position = "right"
    enable_site_search = true
[outputs]
home = ["HTML", "RSS", "JSON"]
[[menu.navbar]]
identifier = "main"
name = "归档"
title = "归档"
url = "/posts/"
weight = 100

